export interface Product {
  name: string;
  category: string;
  estimatedPrice: number;
  annualAppreciation: number;
  description: string;
  emoji: string;
}

export interface Investment {
  name: string;
  symbol: string;
  description: string;
  cagr: number;
  volatility: number;
  bullScenario: number;
  bearScenario: number;
  riskLevel: "low" | "medium" | "high";
  emoji: string;
}

export const PRODUCTS: Product[] = [
  // Watches
  {
    name: "Rolex Submariner",
    category: "Uhren",
    estimatedPrice: 9000,
    annualAppreciation: 0.05,
    description: "Luxus-Sportuhr",
    emoji: "⌚",
  },
  {
    name: "Vintage Patek Philippe",
    category: "Uhren",
    estimatedPrice: 25000,
    annualAppreciation: 0.07,
    description: "Sammlerstück Luxusuhr",
    emoji: "⌚",
  },
  {
    name: "Omega Speedmaster",
    category: "Uhren",
    estimatedPrice: 6000,
    annualAppreciation: 0.04,
    description: "Moonwatch",
    emoji: "⌚",
  },
  {
    name: "Audemars Piguet Royal Oak",
    category: "Uhren",
    estimatedPrice: 32000,
    annualAppreciation: 0.06,
    description: "Ikonische Sportuhr",
    emoji: "⌚",
  },
  {
    name: "Richard Mille RM 11",
    category: "Uhren",
    estimatedPrice: 180000,
    annualAppreciation: 0.03,
    description: "Ultra-Luxus Chronograph",
    emoji: "⌚",
  },
  // Electronics
  {
    name: "iPhone 16 Pro Max",
    category: "Elektronik",
    estimatedPrice: 1599,
    annualAppreciation: -0.15,
    description: "Neuestes Apple Smartphone",
    emoji: "📱",
  },
  {
    name: "MacBook Pro M4",
    category: "Elektronik",
    estimatedPrice: 3499,
    annualAppreciation: -0.1,
    description: "Profi-Laptop",
    emoji: "💻",
  },
  {
    name: "PlayStation 5 Pro",
    category: "Elektronik",
    estimatedPrice: 800,
    annualAppreciation: -0.12,
    description: "Spielkonsole",
    emoji: "🎮",
  },
  {
    name: "Samsung 8K OLED TV",
    category: "Elektronik",
    estimatedPrice: 4500,
    annualAppreciation: -0.18,
    description: "Premium-Fernseher",
    emoji: "📺",
  },
  {
    name: "Vision Pro",
    category: "Elektronik",
    estimatedPrice: 3999,
    annualAppreciation: -0.2,
    description: "AR/VR-Headset",
    emoji: "🥽",
  },
  // Fashion
  {
    name: "Hermès Birkin",
    category: "Mode",
    estimatedPrice: 8000,
    annualAppreciation: 0.08,
    description: "Ikonische Luxus-Handtasche",
    emoji: "👜",
  },
  {
    name: "Louis Vuitton Monogram Bag",
    category: "Mode",
    estimatedPrice: 2500,
    annualAppreciation: 0.04,
    description: "Designer-Handtasche",
    emoji: "👜",
  },
  {
    name: "Chanel Classic Flap",
    category: "Mode",
    estimatedPrice: 9500,
    annualAppreciation: 0.06,
    description: "Klassische Steppledertasche",
    emoji: "👜",
  },
  {
    name: "Canada Goose Parka",
    category: "Mode",
    estimatedPrice: 1200,
    annualAppreciation: -0.2,
    description: "Winterjacke",
    emoji: "🧥",
  },
  // Sneakers
  {
    name: "Air Jordan 1 Retro",
    category: "Sneaker",
    estimatedPrice: 1200,
    annualAppreciation: 0.12,
    description: "Sammler-Sneaker",
    emoji: "👟",
  },
  {
    name: "Nike Dunk Low Travis Scott",
    category: "Sneaker",
    estimatedPrice: 2000,
    annualAppreciation: 0.1,
    description: "Limitierte Kollaboration",
    emoji: "👟",
  },
  {
    name: "Yeezy Boost 350",
    category: "Sneaker",
    estimatedPrice: 400,
    annualAppreciation: -0.05,
    description: "Lifestyle-Sneaker",
    emoji: "👟",
  },
  // Cars
  {
    name: "Porsche 911 Carrera",
    category: "Autos",
    estimatedPrice: 120000,
    annualAppreciation: -0.08,
    description: "Sportwagen",
    emoji: "🚗",
  },
  {
    name: "Ferrari 296 GTB",
    category: "Autos",
    estimatedPrice: 320000,
    annualAppreciation: -0.05,
    description: "Supersportwagen",
    emoji: "🏎️",
  },
  {
    name: "Mercedes G-Klasse",
    category: "Autos",
    estimatedPrice: 140000,
    annualAppreciation: -0.1,
    description: "Luxus-SUV",
    emoji: "🚙",
  },
  {
    name: "Tesla Model S Plaid",
    category: "Autos",
    estimatedPrice: 110000,
    annualAppreciation: -0.15,
    description: "Elektro-Performance-Limousine",
    emoji: "🚗",
  },
  // Jewelry
  {
    name: "Diamant-Solitärring 2ct",
    category: "Schmuck",
    estimatedPrice: 25000,
    annualAppreciation: 0.03,
    description: "Investitionsdiamant",
    emoji: "💍",
  },
  {
    name: "Cartier Love Bracelet",
    category: "Schmuck",
    estimatedPrice: 7500,
    annualAppreciation: 0.05,
    description: "Ikonisches Goldarmband",
    emoji: "💎",
  },
  {
    name: "Rolex Daytona Gold",
    category: "Schmuck",
    estimatedPrice: 45000,
    annualAppreciation: 0.06,
    description: "Goldene Luxusuhr",
    emoji: "💍",
  },
  // Art & Collectibles
  {
    name: "Zeitgenössisches Gemälde",
    category: "Kunst",
    estimatedPrice: 15000,
    annualAppreciation: 0.06,
    description: "Werk eines aufstrebenden Künstlers",
    emoji: "🖼️",
  },
  {
    name: "Pokémon 1st Edition Booster Box",
    category: "Sammlerstücke",
    estimatedPrice: 250000,
    annualAppreciation: 0.15,
    description: "Versiegelte Sammelkarten-Box",
    emoji: "🎴",
  },
  {
    name: "Vintage Comic (CGC 9.8)",
    category: "Sammlerstücke",
    estimatedPrice: 5000,
    annualAppreciation: 0.09,
    description: "Gradeter Sammler-Comic",
    emoji: "📚",
  },
  {
    name: "LEGO Millennium Falcon UCS",
    category: "Sammlerstücke",
    estimatedPrice: 900,
    annualAppreciation: 0.08,
    description: "Versiegeltes Sammler-Set",
    emoji: "🧱",
  },
  // Wine & Spirits
  {
    name: "Château Lafite Rothschild (Kiste)",
    category: "Wein",
    estimatedPrice: 12000,
    annualAppreciation: 0.07,
    description: "Bordeaux-Spitzenwein",
    emoji: "🍷",
  },
  {
    name: "Macallan 25 Jahre",
    category: "Wein",
    estimatedPrice: 3500,
    annualAppreciation: 0.05,
    description: "Rarer Single Malt Whisky",
    emoji: "🥃",
  },
  // Boats
  {
    name: "Motoryacht 10m",
    category: "Boote",
    estimatedPrice: 250000,
    annualAppreciation: -0.06,
    description: "Freizeit-Motorboot",
    emoji: "🛥️",
  },
  // Gaming
  {
    name: "Gaming-PC High-End",
    category: "Gaming",
    estimatedPrice: 4000,
    annualAppreciation: -0.22,
    description: "High-End-Gaming-Rig",
    emoji: "🖥️",
  },
  {
    name: "Nintendo Switch 2",
    category: "Gaming",
    estimatedPrice: 470,
    annualAppreciation: -0.14,
    description: "Hybrid-Spielkonsole",
    emoji: "🎮",
  },
  {
    name: "Xbox Series X",
    category: "Gaming",
    estimatedPrice: 550,
    annualAppreciation: -0.13,
    description: "Spielkonsole",
    emoji: "🎮",
  },
  // More Watches
  {
    name: "Rolex Daytona Panda",
    category: "Uhren",
    estimatedPrice: 38000,
    annualAppreciation: 0.06,
    description: "Begehrter Chronograph",
    emoji: "⌚",
  },
  {
    name: "Casio G-Shock Limited",
    category: "Uhren",
    estimatedPrice: 300,
    annualAppreciation: -0.03,
    description: "Robuste Sammler-Digitaluhr",
    emoji: "⌚",
  },
  // More Electronics
  {
    name: "Samsung Galaxy S26 Ultra",
    category: "Elektronik",
    estimatedPrice: 1450,
    annualAppreciation: -0.17,
    description: "Android-Flaggschiff-Smartphone",
    emoji: "📱",
  },
  {
    name: "iPad Pro M5",
    category: "Elektronik",
    estimatedPrice: 1300,
    annualAppreciation: -0.14,
    description: "Profi-Tablet",
    emoji: "📱",
  },
  {
    name: "DJI Mavic Drohne",
    category: "Elektronik",
    estimatedPrice: 2200,
    annualAppreciation: -0.16,
    description: "Profi-Kameradrohne",
    emoji: "🚁",
  },
  {
    name: "Sony Alpha 1 II Kamera",
    category: "Elektronik",
    estimatedPrice: 6500,
    annualAppreciation: -0.09,
    description: "Profi-Vollformatkamera",
    emoji: "📷",
  },
  // More Fashion
  {
    name: "Ray-Ban Meta Sonnenbrille",
    category: "Mode",
    estimatedPrice: 350,
    annualAppreciation: -0.1,
    description: "Smart-Sonnenbrille",
    emoji: "🕶️",
  },
  {
    name: "Moncler Daunenjacke",
    category: "Mode",
    estimatedPrice: 1800,
    annualAppreciation: -0.15,
    description: "Premium-Winterjacke",
    emoji: "🧥",
  },
  {
    name: "Gucci Gürtel",
    category: "Mode",
    estimatedPrice: 450,
    annualAppreciation: -0.08,
    description: "Designer-Accessoire",
    emoji: "👔",
  },
  // More Sneakers
  {
    name: "Nike Air Mag 'Back to the Future'",
    category: "Sneaker",
    estimatedPrice: 50000,
    annualAppreciation: 0.1,
    description: "Extrem seltener Sammler-Sneaker",
    emoji: "👟",
  },
  {
    name: "Adidas Samba OG",
    category: "Sneaker",
    estimatedPrice: 120,
    annualAppreciation: -0.03,
    description: "Klassischer Lifestyle-Sneaker",
    emoji: "👟",
  },
  // More Cars
  {
    name: "VW Golf GTI",
    category: "Autos",
    estimatedPrice: 45000,
    annualAppreciation: -0.12,
    description: "Kompakter Hot Hatch",
    emoji: "🚗",
  },
  {
    name: "Land Rover Defender",
    category: "Autos",
    estimatedPrice: 95000,
    annualAppreciation: -0.09,
    description: "Geländewagen",
    emoji: "🚙",
  },
  {
    name: "Vintage Mercedes 190 SL",
    category: "Autos",
    estimatedPrice: 150000,
    annualAppreciation: 0.05,
    description: "Klassiker mit Sammlerwert",
    emoji: "🚘",
  },
  // Motorcycles (new category)
  {
    name: "Ducati Panigale V4",
    category: "Motorräder",
    estimatedPrice: 28000,
    annualAppreciation: -0.1,
    description: "Superbike",
    emoji: "🏍️",
  },
  {
    name: "Harley-Davidson Fat Boy",
    category: "Motorräder",
    estimatedPrice: 22000,
    annualAppreciation: -0.06,
    description: "Cruiser-Motorrad",
    emoji: "🏍️",
  },
  // More Jewelry
  {
    name: "Van Cleef & Arpels Alhambra",
    category: "Schmuck",
    estimatedPrice: 6500,
    annualAppreciation: 0.04,
    description: "Ikonisches Schmuckset",
    emoji: "💎",
  },
  {
    name: "Tiffany Diamant-Ohrringe",
    category: "Schmuck",
    estimatedPrice: 9000,
    annualAppreciation: 0.03,
    description: "Diamantschmuck",
    emoji: "💍",
  },
  // More Art & Collectibles
  {
    name: "Limitierter Kunstdruck (Signiert)",
    category: "Kunst",
    estimatedPrice: 3000,
    annualAppreciation: 0.04,
    description: "Signierte Auflage eines bekannten Künstlers",
    emoji: "🖼️",
  },
  {
    name: "Antike Bronzeskulptur",
    category: "Kunst",
    estimatedPrice: 22000,
    annualAppreciation: 0.05,
    description: "Historisches Sammlerstück",
    emoji: "🗿",
  },
  {
    name: "Rolex Submariner NOS (Vintage)",
    category: "Sammlerstücke",
    estimatedPrice: 40000,
    annualAppreciation: 0.08,
    description: "Ungetragene Vintage-Uhr",
    emoji: "🎴",
  },
  {
    name: "Michael Jordan Rookie Card (PSA 9)",
    category: "Sammlerstücke",
    estimatedPrice: 35000,
    annualAppreciation: 0.11,
    description: "Gradete Sammelkarte",
    emoji: "🏀",
  },
  {
    name: "Erstausgabe Roman (Signiert)",
    category: "Sammlerstücke",
    estimatedPrice: 4500,
    annualAppreciation: 0.05,
    description: "Signiertes literarisches Sammlerstück",
    emoji: "📖",
  },
  // More Wine & Spirits
  {
    name: "Dom Pérignon Vintage (Kiste)",
    category: "Wein",
    estimatedPrice: 2500,
    annualAppreciation: 0.04,
    description: "Prestige-Champagner",
    emoji: "🍾",
  },
  {
    name: "Pappy Van Winkle 23",
    category: "Wein",
    estimatedPrice: 5000,
    annualAppreciation: 0.06,
    description: "Seltener Bourbon-Whiskey",
    emoji: "🥃",
  },
  // More Boats
  {
    name: "Jetski",
    category: "Boote",
    estimatedPrice: 15000,
    annualAppreciation: -0.14,
    description: "Wassersportfahrzeug",
    emoji: "🚤",
  },
  // Furniture (new category)
  {
    name: "Le Corbusier LC4 Liege (Original)",
    category: "Möbel",
    estimatedPrice: 6000,
    annualAppreciation: 0.02,
    description: "Design-Klassiker",
    emoji: "🛋️",
  },
  {
    name: "Designer-Küche (High-End)",
    category: "Möbel",
    estimatedPrice: 45000,
    annualAppreciation: -0.05,
    description: "Maßgefertigte Einbauküche",
    emoji: "🍽️",
  },
  // Musical instruments (new category)
  {
    name: "Gibson Les Paul Custom",
    category: "Musikinstrumente",
    estimatedPrice: 5000,
    annualAppreciation: 0.03,
    description: "Ikonische E-Gitarre",
    emoji: "🎸",
  },
  {
    name: "Steinway & Sons Flügel",
    category: "Musikinstrumente",
    estimatedPrice: 90000,
    annualAppreciation: 0.02,
    description: "Konzertflügel",
    emoji: "🎹",
  },
  {
    name: "Vintage Fender Stratocaster (1965)",
    category: "Musikinstrumente",
    estimatedPrice: 35000,
    annualAppreciation: 0.06,
    description: "Vintage-Sammlergitarre",
    emoji: "🎸",
  },
  // Bikes (new category)
  {
    name: "Rennrad High-End (Carbon)",
    category: "Fahrräder",
    estimatedPrice: 9000,
    annualAppreciation: -0.15,
    description: "Profi-Rennrad",
    emoji: "🚴",
  },
  {
    name: "E-Bike Premium",
    category: "Fahrräder",
    estimatedPrice: 5500,
    annualAppreciation: -0.16,
    description: "Elektrofahrrad",
    emoji: "🚲",
  },
];

export const CATEGORY_EMOJIS: Record<string, string> = {
  Uhren: "⌚",
  Elektronik: "📱",
  Mode: "👜",
  Sneaker: "👟",
  Autos: "🚗",
  Schmuck: "💍",
  Kunst: "🖼️",
  Sammlerstücke: "🎴",
  Wein: "🍷",
  Boote: "🛥️",
  Gaming: "🎮",
  Motorräder: "🏍️",
  Möbel: "🛋️",
  Musikinstrumente: "🎸",
  Fahrräder: "🚴",
};

export const INVESTMENTS: Investment[] = [
  {
    name: "Bitcoin",
    symbol: "BTC",
    description: "Kryptowährung",
    cagr: 0.65,
    volatility: 0.75,
    bullScenario: 1.2,
    bearScenario: -0.4,
    riskLevel: "high",
    emoji: "₿",
  },
  {
    name: "Ethereum",
    symbol: "ETH",
    description: "Smart-Contract-Blockchain",
    cagr: 0.45,
    volatility: 0.7,
    bullScenario: 1.15,
    bearScenario: -0.5,
    riskLevel: "high",
    emoji: "◆",
  },
  {
    name: "NVIDIA",
    symbol: "NVDA",
    description: "KI-Chip-Marktführer",
    cagr: 0.5,
    volatility: 0.5,
    bullScenario: 0.6,
    bearScenario: -0.3,
    riskLevel: "high",
    emoji: "🖥️",
  },
  {
    name: "Apple",
    symbol: "AAPL",
    description: "Tech-Konzern",
    cagr: 0.28,
    volatility: 0.3,
    bullScenario: 0.35,
    bearScenario: -0.2,
    riskLevel: "medium",
    emoji: "🍎",
  },
  {
    name: "Tesla",
    symbol: "TSLA",
    description: "Elektrofahrzeuge",
    cagr: 0.32,
    volatility: 0.55,
    bullScenario: 0.5,
    bearScenario: -0.35,
    riskLevel: "high",
    emoji: "⚡",
  },
  {
    name: "MSCI World",
    symbol: "MSCI",
    description: "Globaler Aktienindex",
    cagr: 0.09,
    volatility: 0.15,
    bullScenario: 0.15,
    bearScenario: -0.15,
    riskLevel: "medium",
    emoji: "🌍",
  },
  {
    name: "S&P 500",
    symbol: "SPY",
    description: "US-Aktienindex",
    cagr: 0.1,
    volatility: 0.18,
    bullScenario: 0.18,
    bearScenario: -0.18,
    riskLevel: "medium",
    emoji: "📈",
  },
  {
    name: "FTSE 100",
    symbol: "FTSE",
    description: "UK-Aktienindex",
    cagr: 0.07,
    volatility: 0.16,
    bullScenario: 0.12,
    bearScenario: -0.12,
    riskLevel: "medium",
    emoji: "🇬🇧",
  },
  {
    name: "Tagesgeldkonto",
    symbol: "SAVE",
    description: "Sicheres Sparen (Ø 2,5% p.a.)",
    cagr: 0.025,
    volatility: 0.0,
    bullScenario: 0.025,
    bearScenario: 0.025,
    riskLevel: "low",
    emoji: "💰",
  },
  {
    name: "Immobilien (AT)",
    symbol: "REAL",
    description: "Wiener Immobilie (Wertsteigerung + Mietrendite)",
    cagr: 0.045,
    volatility: 0.08,
    bullScenario: 0.08,
    bearScenario: -0.05,
    riskLevel: "low",
    emoji: "🏠",
  },
  {
    name: "Gold",
    symbol: "GOLD",
    description: "Edelmetall als Wertspeicher",
    cagr: 0.08,
    volatility: 0.14,
    bullScenario: 0.18,
    bearScenario: -0.1,
    riskLevel: "low",
    emoji: "🪙",
  },
];
